language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"
env:
  - NETWORKX_VERSION=1.11
  - NETWORKX_VERSION=2.0
install:
  - pip install -q networkx==$NETWORKX_VERSION
  - pip install -q pytest
  - python setup.py -q build
  - python setup.py -q install
  - pip install pylint
script:
  - pylint graphgen/
  - cd tests && python run_tests.py
